# encoding: utf-8
---
recipe:
  Rx: all
  description: >-
    all content

download_files: >-
  https://raw.githubusercontent.com/iDvel/rime-ice/main/en_dicts/cn_en_flypy.txt

install_files: >-
  *.dict.yaml
  *.schema.yaml
  cn_en_flypy.txt
  zh_CN.txt
  punct.yaml
  fcitx5.yaml
  fira.trime.yaml
  weasel.yaml
  default.yaml
  ibus_rime.yaml
  cn_dicts/*
  en_dicts/*
  preview/*
  opencc/*
  lua/*
  res/*.*
